### ISSUE TITLE
Consider auto-destroying tags with no items

### ISSUE THREAD

**Issue by teceler** [Marri/glowfic#1083]
https://github.com/Marri/glowfic/blob/ad00696b4d2eeb0a3e19aec9fe6adf270a45fd79/app/models/tag.rb#L79-L82

**Comment by teceler** [comment]
(Argument against that I recall is it indicates posts not visible to user, when something stays with 0. Although that doesn't apply to gallery-groups)

**Comment by Marri** [comment]
We can maybe avoid the indication problem with an inner join or a where filter of some kind

**Comment by teceler** [comment]
Duplicate of #536
