### ISSUE TITLE
Most of the Bell images seem to be broken

### ISSUE THREAD

**Issue by AaronSzaboo** [Marri/glowfic#1189]
Link: https://www.glowfic.com/templates/3

**Comment by Marri** [comment]
@AaronSzaboo they work fine for me? But it's worth mentioning that those are mostly hotlinked to Dreamwidth not actually hosted by the Constellation, can you load Dreamwidth more generally?

**Comment by AaronSzaboo** [comment]
Dreamwidth loads fine for me. If I open the hotlink of a broken image (e.g. https://v.dreamwidth.org/4737245/1721567), they also load fine.

Using my phone (Google Chrome browser), everything works fine. That's also true for Internet Explorer and Microsoft Edge on my laptop.

Only with Google Chrome, on laptop, are the images broken like this: https://i.imgur.com/TEVrTYU.png

Not just the Bell images - roughly 80% of Alicorn's images are broken, while only about 10% of Kappa's, lintamande's or Pedro's images. 

Also, on other users, the images seem to broken like this: https://i.imgur.com/4gDdzhb.png instead.

**Comment by Marri** [comment]
@AaronSzaboo interesting; Chrome on my laptop loads all those broken images just fine for me, both the Bells and Serg (and the Serg one the screenshot shows as broken *is* hosted by the Constellation). Does your browser console (right click and go to Inspect then Console) show anything that might be a clue? Often if images fail to load the error output will go there.

The blank outline boxes are us trying to represent characters that have no icon in a fashion consistent with the rest of the UI; that's maybe worth a UI issue to follow up on if it's not clear that that represents the lack of an icon, but they're not a different kind of broken image.

**Comment by AaronSzaboo** [comment]
The browser console shows a "Failed to load resource: net::ERR_BLOCKED_BY_CLIENT" error. Since google said it's probably caused by an adblock extension, I tried turning them off.

In the end, the problem was Privacy Badger blocking the links to Dreamwidth.

Sorry for bothering you.

**Comment by Marri** [comment]
@AaronSzaboo Not a problem at all! Thank you for reporting, and I'll go note the confusing UI separately :)
