### ISSUE TITLE
API Improvements

### ISSUE THREAD

**Issue by dhouck** [Marri/glowfic#1211]
It would be useful if the following information were available in the API, not just through the main UI:

* [x] Threads in a continuity or subcontinuity; currently you can only get subcontinuities in a continuity and cannot get information about a subcontinuity, just reorder them.
  * [x] List of threads by subcontinuity
  * [x] Order within subcontinuity
* [x] Top post available when looking at a thread in the API
* [x] More details on a user. In particular:
  * [x] Color name and hex code
  * [x] List of posts the user participates in

**Comment by l1n** [comment]
More details on the user looks like it has been fulfilled, see 2400dca86

**Comment by dhouck** [comment]
And that seems to be everything, although “order within subcontinuity” is a bit weird because sometimes there are holes.  My two guesses are that either itʼs a leftover from reordering things, or itʼs leaking information about hidden threads.
