### ISSUE TITLE
Set HSTS preload headers

### ISSUE THREAD

**Issue by Marri** [Marri/glowfic#1347]
See <https://blog.bigbinary.com/2016/08/24/rails-5-adds-more-control-to-fine-tuning-ssl-usage.html>

**Comment by Marri** [comment]
It appears we do set them correctly on HTTPS and they are rightfully ignored on HTTP in case an attacker has modified them. So, closing.

**Comment by Throne3d** [comment]
Reopening for preload:

```rb
config.ssl_options = { hsts: { preload: true } }
```

Also https://hstspreload.org/
