### ISSUE TITLE
Stats page doesn't have og_data

### ISSUE THREAD

**Issue by teceler** [Marri/glowfic#1434]
I just linked to the stats page of a post and it didn't produce og data despite being public. This seems suboptimal and would be nice to fix.

**Comment by l1n** [comment]
This has been fixed in #1467, ok to close?

**Comment by Marri** [comment]
Yep thanks for pointing it out, closing. I think it'll do it automatically if your PR description is "Fixes" instead of "for" or something like that? I'd have to double check the exact Github magic.
