### ISSUE TITLE
Allow post creators to swap ownership

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#147]
I have no idea if they want this to edit the UI of (display of who authored) the first post. This is probably not very useful right now but might be in the future.

See [here](http://alicorn.elcenia.com/board/viewtopic.php?f=12&t=459&start=1910#p32099).

**Comment by Throne3d** [comment]
Possibly relates to #74.

**Comment by teceler** [comment]
Probably obsolete with PostAuthors existing.
