### ISSUE TITLE
Marking a whole board read is implemented weirdly

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#149]
If you mark a board as read, it should mark all posts in the board at that time as read so that posts can be individually marked unread. The current system is iffy (as you can't seem to mark individual posts unread).

I guess it saves database space? But we need some sort of flag to make people able to mark individual posts unread ("override board read with this post read"?) or we need to convert it when it conflicts with other usage.

I also don't know if you can remove the board read? With a post you'd mark it read and then go to its menu to mark it unread – is that doable in the UI for users?

**Comment by Throne3d** [comment]
@Marri I'd appreciate input on this at some point.

**Comment by Throne3d** [comment]
I guess hiding a board makes sense, but not so much *reading* a board (at least in my opinion), except insofar as that should read every individual post at that point.

**Comment by Throne3d** [comment]
The main concern was previously database rows. This is definitely a consideration.

Since we have `read_at` distinguished from `updated_at`, now (I think), we should be able to override a board view with the relevant post view. If a post is marked unread, simply reset its `read_at` but update its `updated_at`, then pay attention to the fact it's not read, despite the rest of the board being so.

**Comment by teceler** [comment]
Fixed in #1127
