### ISSUE TITLE
Investigate post views being destroyed erroneously

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#169]
> I am seeing a problem where the Constellation forgets — not immediately — that I've started reading a thread. In particular, I think I have twice now found [Why does the dungeon always collapse](https://www.glowfic.com/posts/728) back to unopened. And yet now, and I think the last time, I have partially read it and it shows up in my unread list like normal.

-[Unbitwise](http://alicorn.elcenia.com/board/viewtopic.php?f=12&t=459&start=1970#p32456)

I have no idea how to reproduce this but perhaps there's some obvious route in the code that's wrong?

**Comment by Marri** [comment]
Sounds like this was from using glowfic.com / www.glowfic.com incorrectly; closing unless we see more reports.
