### ISSUE TITLE
Improve NPC switching

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#24]
> Make it faster/easier to switch to base account, to disincentivize posting NPCs as a named character who they are not.

**Comment by Throne3d** [comment]
Related to #34: allow replying to a post (/ creating a post) as a setting, i.e. using a setting as a character.

**Comment by Marri** [comment]
Also [requested by Moriwen](http://alicorn.elcenia.com/board/viewtopic.php?f=12&t=459&start=1790#p31710): improve switching between just-the-two-characters-I've-used-in-this-thread. May not scale well.

**Comment by Throne3d** [comment]
(In the above link there are details about suggested implementation.)

**Comment by Throne3d** [comment]
Probably almost entirely fixed by the new quick switcher (#211) which was apparently suggested by Moriwen! Gosh, I thought I'd come up with the idea myself, but unless I mysteriously came up with it independently, apparently not.
