### ISSUE TITLE
Editing icons/characters does not update flat views

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#252]
Check on this. I don't recall if they do or not. I don't expect they would, skipping validations, but maybe they do.

**Comment by Throne3d** [comment]
Relatedly: character name changes, screenname changes.

This could be solved (somewhat) by allowing people to flag posts as needing a flat view regeneration, if changes like that are made. Alternatively we could just make sure to requeue all relevant posts.

Semi-relatedly is to paginate flat view (not in display, just in generation), so we put a hard cap on how many things we have to regenerate at a time when a post is just being updated. This prevents RoR-esque collapses.

**Comment by Marri** [comment]
#631 solves this for icons and character replacements but not for changing the information of the character/icon model itself such as character name or screenname. As mentioned, #796 may provide the thing well enough.
