### ISSUE TITLE
Cross-domain cookies interact weirdly

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#269]
You can't seem to log out on [domain you didn't log in on], not properly. It's weird. It logs you back in.

(Noticed first by me but I forgot to bug report it, and again by Pedro.)

**Comment by Throne3d** [comment]
I can't seem to reproduce this anymore.

**Comment by Throne3d** [comment]
See #310.

**Comment by Marri** [comment]
Should this be closed now?

**Comment by Throne3d** [comment]
I haven't seen the problem in a while so I think so.
