### ISSUE TITLE
Investigate InvalidAuthenticityToken errors

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#282]
Currently people are getting mysterious `InvalidAuthenticityToken` errors. Authenticity tokens are a thing done automatically by Rails when using destructive methods (e.g. POST), and we currently have session to never expire, so we're not entirely sure what's up with this. It started approximately when we moved to Rails 4.

Ideas to investigate:

- Somehow the session is still expiring, possibly due to a long time elapsing without the form submission

Things to fix:

- [x] Users are logging out and back in (possibly _being logged out_, since we've been having some issues with that), which makes the old form invalid; we could fix this with a JavaScript note to reload the page (see #296)

Keywords: CSRF

**Comment by Throne3d** [comment]
Latter suggestion repros.

**Comment by Throne3d** [comment]
Recommendation to check for log-in, as our cookies appear to be HTTP-only (that is, transport-only, as opposed to being dynamically modified, meaning JavaScript cannot tamper with them), is to set a `localStorage` value for `loggedIn` → `true`, and in other tabs use the `storage` event ([see here](https://developer.mozilla.org/en-US/docs/Web/Events/storage)) to catch the change and display a message to reload.

**Comment by Throne3d** [comment]
See #269. Also something needs to be done about page timeouts, but I'm not sure how to do that without implementing a `POST /ping` endpoint or such.

**Comment by Throne3d** [comment]
It looks better since upgrading to Rails 5 but it's still definitely not fixed.

**Comment by Throne3d** [comment]
We could rescue from InvalidAuthenticityToken exceptions by presenting the user with a page saying their session has expired, and also by clearing their session. I think this is only not recommended when you're not sure you're clearing their session successfully, so possibly we should clear the session and then _redirect_, so we don't have traces of the old session left in the request.

**Comment by teceler** [comment]
Handled with #1102
