### ISSUE TITLE
Admin and moderator options

### ISSUE THREAD

**Issue by Marri** [Marri/glowfic#3]
Things to start with:
- [x] Users can be admin, moderator, or user
- [ ] CRUD to change states
- [x] Admin (Marri) can see everything and do anything
- [ ] Moderators can pin continuities
- [x] Moderators can edit posts or replies
- [x] Admins or moderators editing someone else's post is tracked correctly in audit history.
- [ ] Moderators can create, edit, delete, or merge tags

Longer term:
- [x] Users can have role(s)
- [x] Roles can have permission(s)
- [ ] All the above get their own permissions

**Comment by Throne3d** [comment]
[Mention about griefing potential](http://alicorn.elcenia.com/board/viewtopic.php?f=12&t=459&start=1910#p32099).

**Comment by Throne3d** [comment]
Relatedly: thing requested by lintamande where other people can do organization for them instead of having to report it and have them fix it. (Templates categorization, facecasts, typos…)

**Comment by Throne3d** [comment]
Closing in favor of follow-up #715.
