### ISSUE TITLE
Add settings/worlds/canons

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#34]
- [x] Convert character settings into a tag, link to post settings
- [x] Allow characters multiple settings? (Where they come from, where they find themselves living in major continuities they're a part of, …?)
- [ ] Allow them to be owned by (plural) people
- [ ] Possibly allow them to have marked editors who have permission to state canon about the world (but aren't necessarily owners)
- [x] Allow them to have descriptions
- [x] Ensure to list posts written in them
- ~~Divide setting and canon so you can have multiple settings (e.g. forest vs candy Arda, Chamomile vs Alethia) that tie to the same canon (Tolkien, HDM, etc); consider using a plural "Source" tag instead of a single "Canon" for this, so worlds like Peace can reference both X-Men and Ender's, and worlds like Mîr can reference Silmarillion and PMMM, without claiming they exist in the canon.~~
- [ ] Have some 'standard' settings (mostly canons, like "Harry Potter") that are moderator-controlled (see #3)
- [ ] Make visible as a list on a user's page, requested [here](http://alicorn.elcenia.com/board/viewtopic.php?f=12&t=459&start=1580#p30548) – mention settings they are author of / editor of distinctly from settings they've written in (#537)

**Comment by Throne3d** [comment]
#226 has started to make it easier for us to develop more tags! This might happen soon.

**Comment by Throne3d** [comment]
For worlds like Peace where there are two relevant canons (Ender's Game, X-Men?) it would be useful to be able to attach both things.

Also for worlds that are original but want to quote an inspiring material (original or fanfictional), it would be useful to be able to list those.

Kappa suggests "Source" instead of "Canon", to allow for this.

**Comment by Marri** [comment]
Welp apparently this isn't a thing any more >_>

**Comment by Throne3d** [comment]
Closing in favor of follow-up issue #714.
