### ISSUE TITLE
Live chat (à la Mibbit)

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#38]

**Comment by dhouck** [comment]
Could this be solved with just a link to Discord?

**Comment by Throne3d** [comment]
We had IRC at the time the issue was created on Bitbucket (by @Marri; I just transferred these across to GitHub) so I assumed this was somehow separately desirable.

I expect it could be quite well solved by just linking to Discord (perhaps with the link to the forum, see #221, which I keep thinking should be added to that help menu that we're yet to implement, see #78).

**Comment by Marri** [comment]
Now that we have the link to Discord/IRC on the homepage I'm fine closing this; people are welcome to ping if that's not adequate.
