### ISSUE TITLE
Investigate extracting email CSS so it's not inline

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#400]
Also maybe format the layout according to what the user has selected on the site? Less sure of that. Relates to #398 and the display of the first and last paragraphs in message and reply content.

**Comment by Marri** [comment]
I continue to be reasonably sure that emails disallow inline CSS, yes/no?

**Comment by Throne3d** [comment]
You mean, disallow `<style>…</style>` at the start and using classes or something like that? Gmail doesn't seem to show the formatting if you do that, no (but Thunderbird for example does).
