### ISSUE TITLE
Icon improvements

### ISSUE THREAD

**Issue by Marri** [Marri/glowfic#522]
Requested by Moriwen on the forum:

- [x] If you click on a gallery tag to view all the galleries with that tag, the resulting page doesn't have any of the manage/expand options that the general Galleries page does; it would be handy if it did.

- [x] It feels odd that deleting icons while you're on the main Galleries page (via the expandy feature!) redirects you to the page of that particular gallery, rather than back to the main page.

- [x] It would be super-bonus-handy if, when you're redirected to the Galleries page (e.g. by deleting a gallery), it put you back to the spot on the page where you started from, so you didn't have to scroll down and try to find your place again.

- [ ] Right now, when you're selecting icons to ad to a gallery, half the time you do this by clicking on the icon and having it highlighted (when adding new icons to an existing gallery) and half the time by clicking on a square in the corner of the icon (when adding new icons to a gallery you're just creating (I love that you can do this now!!)) It might make more sense to have those match? In either case, a "select all in this gallery" (and corresponding "select all ungalleried icons") clickbox would be handy for me fairly often. (See #544.)

- [ ] It would be cool if galleries had a "show instances using this gallery" list somewhere, corresponding to each instance's list of galleries it uses. (See #144.)

**Comment by Marri** [comment]
First three complete as of #521. (nb I will not be worrying about returning to place-in-list for deleting_Galleries_ specifically, since I cannot redirect to the gallery I just deleted, but removing icons from a gallery and deleting icons both do the thing correctly.)

**Comment by Throne3d** [comment]
Closing in favor of separate issues.
