### ISSUE TITLE
Post lists can imply information about hidden posts

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#560]
There are a few ways we can divine information about posts from post lists, especially when making use of the search feature.

- If a page of results only has 24 items on it, we know there's a hidden post in this list. (It only has 24 items on it because we load 25, select for only ones that are visible, and use that lot.)
- If there are two pages of results and 26 total items, but the second page of results is empty, we know there's a hidden post at the end. (We don't check the last page of results to see if it has any visible posts before showing it in the paginator.)

These might both be hard to fix (and in fact haven't been tested, but I think they're both true), but they should be noted anyway.

**Comment by Marri** [comment]
@teceler's scoping work has fixed this reasonably well, closing.
