### ISSUE TITLE
Make sure the reply editor doesn't blend into other posts in any layout

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#590]
The even/odd divide got a bit screwed up when we moved to doing it purely through CSS. We should see if we can find a proper selector for the reply editor that works, properly, and figure out a proper solution for this thing.

Make sure to check a variety of layouts. The starries handle it differently, I think, so some of them do it properly and others don't. Especially check a post with no replies, a post with one reply, and a post with two replies.

**Comment by teceler** [comment]
Should be easier to compare the layout css when I finish clawing that into some vague semblance of organization

**Comment by Marri** [comment]
Duplicate of #501
