### ISSUE TITLE
Crop/resize icons when uploading

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#594]
In the case of non-square icons, users may wish to be able to upload them and crop them on the site using JavaScript. It may be hard to integrate this UI with the current upload interface, and it may also be hard to create the interface (allowing a modified image to be created and then saved).

This was possible on Dreamwidth, at least (especially?) for images that are over 100px × 100px.

In case of square icons, resize smaller if over a certain size (e.g. 300x300 is livable, 2400x2400 is probably worth tweaking.)

**Comment by teceler** [comment]
Warning for it (if it doesn't already?) and letting the user edit on their end would likely be easier and could work at least as a short term fix?

**Comment by teceler** [comment]
Images over 400x400 resized to less than that in #1174, I assume this does something sane with non-square icons
