### ISSUE TITLE
Clean up orders to be more deterministic

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#668]
Where we sort by a set of values that can be equal and conflict, it uses arbitrary database ordering (usually based on "when was this row last edited" but not always). This is inconvenient as it means some things can float around in lists. We should fix this by making sure orders are unique.

Example locations (incomplete list):

- [ ] character lists only sort by lowercased character names; these should probably sort next by screenname and then by ID, but the middle part is optional here

**Comment by teceler** [comment]
- [ ] icons do this when keyword is the same, (at least on character#edit). should probably sort by id next.
- [ ] threads do this (at least in recently updated, likely also in other places) when tagged_at is the same. should probably sort by lowercased name and then id
- [ ] tags do this when created_at is the same. should probably sort by lowercased name, or just by id

relatedly icons factory doesn't unique keywords.

**Comment by teceler** [comment]
- [ ] Gallery tags, specifically, do not appear to be sorted at all on gallery#show

**Comment by teceler** [comment]
Fixed in #680
