### ISSUE TITLE
Validate user owns icons when adding them to a gallery

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#671]
Currently an attacker could use a hand-crafted submission to add someone else's icons to their gallery.

**Comment by Throne3d** [comment]
Apparently this is already done – galleries_controller.rb discards icons that aren't owned by the current user on `#icon`.

**Comment by teceler** [comment]
see: https://github.com/Marri/glowfic/blob/1ed120ad3016de8c113d290f70b3406f8d6b1950/app/controllers/galleries_controller.rb#L126
