### ISSUE TITLE
Upgrade to Rails 4

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#69]
Actually perform the upgrade.

- Change the Rails version
- Remove the 'assets' group (make them into normal gems)
- Add the `protected_attributes` gem
- Perform `bundle update`
- Change all `has_many :through` things to use scopes
- Remove any `find_by_…`s that aren't `find_by_id`
- Add `attr_accessible`s to models as appropriate
- Put `confirm:` and `disable_with:`s into `data:` hashes in `link_to` helpers in views
- Make the login POST and login GET routes use different names (e.g. `new_session` for the GET route)
    - Old: `match '/login' => 'sessions#new', :as => :login, :via => :get`
    + New: `match '/login' => 'sessions#new', :as => :new_session, :via => :get`
- Add `request_uuid` to audits (there's a specific rails helper to produce the migration)

**Comment by dhouck** [comment]
Was this not done by 5949e1a or earlier?

**Comment by Throne3d** [comment]
It was done by 432ece889eb512f64e83c5d9464aa87fb7ffc52e actually but yes it's now done.

… We should probably upgrade to Rails 4.2 at some point.
