### ISSUE TITLE
Icon upload enhancements

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#8]
- [x] UI when changing the icon to be uploaded (currently displays both filenames)
- [x] Delete the old icon if you change path of an uploaded icon
- [x] Delete the old icon if the icon's row is deleted on `galleries#add_new`
- [x] Allow uploaded icons to be changed (currently doable by uploading a new icon and then using the 'replace icon' tool)
- [x] Handle errors properly with multi-upload ('Can't display the filename when rendering the error page in galleries#icon')
- [ ] Sort the list as icons upload, especially with multi-upload
- [x] Show a preview of the image once it's uploaded

**Comment by Marri** [comment]
Some progress made in #409

**Comment by Throne3d** [comment]
Icon sorting may not be necessary tbh?

**Comment by Marri** [comment]
I think you are right that icon sorting was probably as an alternative to icon previews; going to close for now, can revisit if requested.
