### ISSUE TITLE
Improve semantic-th selector

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#826]
Here, we use just `th` to select all headers on the page:
https://github.com/Marri/glowfic/blob/4612a0da3e607ebe67bed8ee6af0faaa8e45c908/app/assets/stylesheets/layout.scss#L142
Since we use `th` all over the place in this exact way, this is normally fine, but it does break stuff around `.post-content`s having tables. Since we _don't_ in fact want all `th` styled this way – and we override it with `.sub` and whatnot in all sorts of places – could we make only `th` that _should_ be styled this way have a class, or otherwise mutate this selector, so we only catch the ones we want to?

Follow-up to #825, which overrides the styling just for `post-content`s.

**Comment by teceler** [comment]
Resolved in #837
