### ISSUE TITLE
Change private messages to not use the .post-screenname selector

### ISSUE THREAD

**Issue by teceler** [Marri/glowfic#843]
A mixin can probably be used for common components, and that would avoid needing some ugly hacks we currently are using to work around this.

(see `.post-screenname, .post-screenname a, .post-screenname a:visited` selector in starries, for example)

**Comment by Throne3d** [comment]
Yeah, semantically this is currently incorrect. Fixing it – and thereby unifying, more accurately, the parts in common between the message and reply interfaces – would be good.

**Comment by Marri** [comment]
Duplicate of #580
