### ISSUE TITLE
Replace sass with sassc

### ISSUE THREAD

**Issue by Marri** [Marri/glowfic#891]
@teceler got this in the last gem upgrade #885 

> Post-install message from sass:
> Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.
> 
> If you use Sass as a command-line tool, we recommend using Dart Sass, the new
> primary implementation: https://sass-lang.com/install
> 
> If you use Sass as a plug-in for a Ruby web framework, we recommend using the
> sassc gem: https://github.com/sass/sassc-ruby#readme
> 
> For more details, please refer to the Sass blog:
> http://sass.logdown.com/posts/7081811

We should replace sass with sassc as instructed. Should occur after we have more view / CSS tests.

**Comment by teceler** [comment]
Done in #1042
